{% set version = "0.0.2" %}

package:
  name: ironcub-models
  version: {{ version }}

source:
  url: "https://github.com/ami-iit/ironcub-models/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 493dc82317c88a38cdf9b779ab7cc44cf59ef2f761e509c32484af340b0c7c1c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - cmake
    - pkg-config
    - ninja
    - multisheller
  host:
    # explicitly empty
  run:
    - __unix  # [unix]
    - __win   # [win]

test:
  commands:
    - test -f ${PREFIX}/share/iRonCub-Mk3/iRonCub/robots/iRonCub-Mk3/model.urdf  # [unix]
    - if not exist %LIBRARY_PREFIX%\\share\\iRonCub-Mk3\\iRonCub\\robots\\iRonCub-Mk3\\model.urdf exit 1  # [win]

about:
  home: https://github.com/ami-iit/ironcub-models
  license: BSD-3-Clause
  license_file: LICENSE
  summary: URDF and XML models of the iRonCub humanoid robot.

extra:
  recipe-maintainers:
    - davidegorbani
